[2025-03-12T15:21:16.002+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T15:21:16.021+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.transform_raw_to_staging manual__2025-03-12T15:20:57.288293+00:00 [queued]>
[2025-03-12T15:21:16.031+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.transform_raw_to_staging manual__2025-03-12T15:20:57.288293+00:00 [queued]>
[2025-03-12T15:21:16.032+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-12T15:21:16.046+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_raw_to_staging> on 2025-03-12 15:20:57.288293+00:00
[2025-03-12T15:21:16.051+0000] {standard_task_runner.py:72} INFO - Started process 307 to run task
[2025-03-12T15:21:16.056+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'transform_raw_to_staging', 'manual__2025-03-12T15:20:57.288293+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmp1i2phpup']
[2025-03-12T15:21:16.062+0000] {standard_task_runner.py:105} INFO - Job 173: Subtask transform_raw_to_staging
[2025-03-12T15:21:16.089+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-12T15:21:16.131+0000] {task_command.py:467} INFO - Running <TaskInstance: data_lake_pipeline.transform_raw_to_staging manual__2025-03-12T15:20:57.288293+00:00 [running]> on host ***-scheduler
[2025-03-12T15:21:16.225+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='transform_raw_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T15:20:57.288293+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T15:20:57.288293+00:00'
[2025-03-12T15:21:16.227+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T15:21:16.243+0000] {manage_buckets.py:44} INFO - [Data manager] Prefix(s) : ['test', 'train', 'validation']
[2025-03-12T15:21:16.243+0000] {manage_buckets.py:46} INFO - [Data manager] Processessing data from : test
[2025-03-12T15:21:16.244+0000] {aws_s3_repository.py:33} INFO - [AWS S3] Getting list of raw's files...
[2025-03-12T15:21:16.278+0000] {aws_s3_repository.py:38} INFO - [AWS S3]ðŸ“¥ Download ResponseMetadata from raw...
[2025-03-12T15:21:16.291+0000] {aws_s3_repository.py:51} CRITICAL - [AWS S3] Error while processing data raw ... : An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
[2025-03-12T15:21:16.292+0000] {manage_buckets.py:46} INFO - [Data manager] Processessing data from : train
[2025-03-12T15:21:16.292+0000] {aws_s3_repository.py:33} INFO - [AWS S3] Getting list of raw's files...
[2025-03-12T15:21:16.313+0000] {aws_s3_repository.py:38} INFO - [AWS S3]ðŸ“¥ Download ResponseMetadata from raw...
[2025-03-12T15:21:16.319+0000] {aws_s3_repository.py:51} CRITICAL - [AWS S3] Error while processing data raw ... : An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
[2025-03-12T15:21:16.319+0000] {manage_buckets.py:46} INFO - [Data manager] Processessing data from : validation
[2025-03-12T15:21:16.319+0000] {aws_s3_repository.py:33} INFO - [AWS S3] Getting list of raw's files...
[2025-03-12T15:21:16.338+0000] {aws_s3_repository.py:38} INFO - [AWS S3]ðŸ“¥ Download ResponseMetadata from raw...
[2025-03-12T15:21:16.344+0000] {aws_s3_repository.py:51} CRITICAL - [AWS S3] Error while processing data raw ... : An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
[2025-03-12T15:21:16.345+0000] {manage_buckets.py:57} ERROR - [Data manager] Data processing failed.
[2025-03-12T15:21:16.345+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T15:21:16.357+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T15:21:16.358+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=transform_raw_to_staging, run_id=manual__2025-03-12T15:20:57.288293+00:00, execution_date=20250312T152057, start_date=20250312T152116, end_date=20250312T152116
[2025-03-12T15:21:16.438+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T15:21:16.456+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-12T15:21:16.461+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
