[2025-03-12T16:43:24.093+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T16:43:24.113+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.transform_raw_to_staging manual__2025-03-12T16:42:55.439980+00:00 [queued]>
[2025-03-12T16:43:24.122+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.transform_raw_to_staging manual__2025-03-12T16:42:55.439980+00:00 [queued]>
[2025-03-12T16:43:24.123+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-12T16:43:24.136+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_raw_to_staging> on 2025-03-12 16:42:55.439980+00:00
[2025-03-12T16:43:24.142+0000] {standard_task_runner.py:72} INFO - Started process 277 to run task
[2025-03-12T16:43:24.145+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'transform_raw_to_staging', 'manual__2025-03-12T16:42:55.439980+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmpohlp87vm']
[2025-03-12T16:43:24.147+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask transform_raw_to_staging
[2025-03-12T16:43:24.165+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-12T16:43:24.196+0000] {task_command.py:467} INFO - Running <TaskInstance: data_lake_pipeline.transform_raw_to_staging manual__2025-03-12T16:42:55.439980+00:00 [running]> on host ***-scheduler
[2025-03-12T16:43:24.263+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='transform_raw_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T16:42:55.439980+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T16:42:55.439980+00:00'
[2025-03-12T16:43:24.264+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T16:43:24.275+0000] {manage_buckets.py:44} INFO - [Data manager] Prefix(s) : ['test', 'train', 'validation']
[2025-03-12T16:43:24.275+0000] {manage_buckets.py:46} INFO - [Data manager] Processessing data from : test
[2025-03-12T16:43:24.276+0000] {aws_s3_repository.py:33} INFO - [AWS S3] Getting list of raw's files...
[2025-03-12T16:43:24.290+0000] {aws_s3_repository.py:54} CRITICAL - [AWS S3] Error while processing data raw ... : An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2025-03-12T16:43:24.290+0000] {manage_buckets.py:46} INFO - [Data manager] Processessing data from : train
[2025-03-12T16:43:24.291+0000] {aws_s3_repository.py:33} INFO - [AWS S3] Getting list of raw's files...
[2025-03-12T16:43:24.297+0000] {aws_s3_repository.py:54} CRITICAL - [AWS S3] Error while processing data raw ... : An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2025-03-12T16:43:24.298+0000] {manage_buckets.py:46} INFO - [Data manager] Processessing data from : validation
[2025-03-12T16:43:24.298+0000] {aws_s3_repository.py:33} INFO - [AWS S3] Getting list of raw's files...
[2025-03-12T16:43:24.303+0000] {aws_s3_repository.py:54} CRITICAL - [AWS S3] Error while processing data raw ... : An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2025-03-12T16:43:24.304+0000] {manage_buckets.py:57} ERROR - [Data manager] Data processing failed.
[2025-03-12T16:43:24.304+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T16:43:24.313+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T16:43:24.314+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=transform_raw_to_staging, run_id=manual__2025-03-12T16:42:55.439980+00:00, execution_date=20250312T164255, start_date=20250312T164324, end_date=20250312T164324
[2025-03-12T16:43:24.365+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T16:43:24.380+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-12T16:43:24.385+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
