[2025-03-12T15:20:35.834+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T15:20:35.870+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.transform_raw_to_staging manual__2025-03-12T15:20:16.112107+00:00 [queued]>
[2025-03-12T15:20:35.888+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.transform_raw_to_staging manual__2025-03-12T15:20:16.112107+00:00 [queued]>
[2025-03-12T15:20:35.888+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-12T15:20:35.914+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_raw_to_staging> on 2025-03-12 15:20:16.112107+00:00
[2025-03-12T15:20:35.924+0000] {standard_task_runner.py:72} INFO - Started process 238 to run task
[2025-03-12T15:20:35.934+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'transform_raw_to_staging', 'manual__2025-03-12T15:20:16.112107+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmpkylzwqcy']
[2025-03-12T15:20:35.937+0000] {standard_task_runner.py:105} INFO - Job 169: Subtask transform_raw_to_staging
[2025-03-12T15:20:35.965+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-12T15:20:36.017+0000] {task_command.py:467} INFO - Running <TaskInstance: data_lake_pipeline.transform_raw_to_staging manual__2025-03-12T15:20:16.112107+00:00 [running]> on host ***-scheduler
[2025-03-12T15:20:36.157+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='transform_raw_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T15:20:16.112107+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T15:20:16.112107+00:00'
[2025-03-12T15:20:36.158+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T15:20:36.173+0000] {manage_buckets.py:44} INFO - [Data manager] Prefix(s) : ['test', 'train', 'validation']
[2025-03-12T15:20:36.173+0000] {manage_buckets.py:46} INFO - [Data manager] Processessing data from : test
[2025-03-12T15:20:36.174+0000] {aws_s3_repository.py:33} INFO - [AWS S3] Getting list of raw's files...
[2025-03-12T15:20:36.206+0000] {aws_s3_repository.py:38} INFO - [AWS S3]ðŸ“¥ Download ResponseMetadata from raw...
[2025-03-12T15:20:36.220+0000] {aws_s3_repository.py:51} CRITICAL - [AWS S3] Error while processing data raw ... : An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
[2025-03-12T15:20:36.222+0000] {manage_buckets.py:46} INFO - [Data manager] Processessing data from : train
[2025-03-12T15:20:36.223+0000] {aws_s3_repository.py:33} INFO - [AWS S3] Getting list of raw's files...
[2025-03-12T15:20:36.251+0000] {aws_s3_repository.py:38} INFO - [AWS S3]ðŸ“¥ Download ResponseMetadata from raw...
[2025-03-12T15:20:36.257+0000] {aws_s3_repository.py:51} CRITICAL - [AWS S3] Error while processing data raw ... : An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
[2025-03-12T15:20:36.258+0000] {manage_buckets.py:46} INFO - [Data manager] Processessing data from : validation
[2025-03-12T15:20:36.258+0000] {aws_s3_repository.py:33} INFO - [AWS S3] Getting list of raw's files...
[2025-03-12T15:20:36.288+0000] {aws_s3_repository.py:38} INFO - [AWS S3]ðŸ“¥ Download ResponseMetadata from raw...
[2025-03-12T15:20:36.294+0000] {aws_s3_repository.py:51} CRITICAL - [AWS S3] Error while processing data raw ... : An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
[2025-03-12T15:20:36.294+0000] {manage_buckets.py:57} ERROR - [Data manager] Data processing failed.
[2025-03-12T15:20:36.295+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T15:20:36.305+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T15:20:36.306+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=transform_raw_to_staging, run_id=manual__2025-03-12T15:20:16.112107+00:00, execution_date=20250312T152016, start_date=20250312T152035, end_date=20250312T152036
[2025-03-12T15:20:36.355+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T15:20:36.375+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-12T15:20:36.382+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
