[2025-03-12T21:29:17.318+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T21:29:17.347+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_raw manual__2025-03-12T21:29:08.864088+00:00 [queued]>
[2025-03-12T21:29:17.359+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_raw manual__2025-03-12T21:29:08.864088+00:00 [queued]>
[2025-03-12T21:29:17.360+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-12T21:29:17.376+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_to_raw> on 2025-03-12 21:29:08.864088+00:00
[2025-03-12T21:29:17.384+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-03-12T21:29:17.399+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'process_to_raw', 'manual__2025-03-12T21:29:08.864088+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmpg7vbvomk']
[2025-03-12T21:29:17.402+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask process_to_raw
[2025-03-12T21:29:17.447+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-12T21:29:17.525+0000] {task_command.py:467} INFO - Running <TaskInstance: data_lake_pipeline.process_to_raw manual__2025-03-12T21:29:08.864088+00:00 [running]> on host ***-scheduler
[2025-03-12T21:29:17.671+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='process_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T21:29:08.864088+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T21:29:08.864088+00:00'
[2025-03-12T21:29:17.675+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T21:29:17.698+0000] {manage_buckets.py:24} INFO - [Data manager] Downloading data from HuggingFace...
[2025-03-12T21:29:21.618+0000] {logging_mixin.py:190} WARNING - Generating test split:   0%|          | 0/4358 [00:00<?, ? examples/s]
[2025-03-12T21:29:21.735+0000] {logging_mixin.py:190} WARNING - Generating test split:  23%|##2       | 1000/4358 [00:00<00:00, 8732.51 examples/s]
[2025-03-12T21:29:21.744+0000] {logging_mixin.py:190} WARNING - Generating test split: 100%|##########| 4358/4358 [00:00<00:00, 35004.74 examples/s]
[2025-03-12T21:29:21.746+0000] {logging_mixin.py:190} WARNING - Generating train split:   0%|          | 0/36718 [00:00<?, ? examples/s]
[2025-03-12T21:29:21.848+0000] {logging_mixin.py:190} WARNING - Generating train split:  60%|#####9    | 22000/36718 [00:00<00:00, 216773.65 examples/s]
[2025-03-12T21:29:21.887+0000] {logging_mixin.py:190} WARNING - Generating train split: 100%|##########| 36718/36718 [00:00<00:00, 261336.62 examples/s]
[2025-03-12T21:29:21.889+0000] {logging_mixin.py:190} WARNING - Generating validation split:   0%|          | 0/3760 [00:00<?, ? examples/s]
[2025-03-12T21:29:21.906+0000] {logging_mixin.py:190} WARNING - Generating validation split: 100%|##########| 3760/3760 [00:00<00:00, 235325.64 examples/s]
[2025-03-12T21:29:21.929+0000] {manage_buckets.py:27} INFO - [Data manager] Data successfully downloaded.
[2025-03-12T21:29:21.930+0000] {manage_buckets.py:30} INFO - [Data manager] Transferring data to S3 bucket...
[2025-03-12T21:29:21.931+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/app/src/command/manage_buckets.py", line 31, in ingest_data
    response = aws_s3.upload_files_into_multiple_folders_test(Bucket=bucket_name, data=data, folders=split)
AttributeError: 'AwsS3Repository' object has no attribute 'upload_files_into_multiple_folders_test'
[2025-03-12T21:29:21.970+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=data_lake_pipeline, task_id=process_to_raw, run_id=manual__2025-03-12T21:29:08.864088+00:00, execution_date=20250312T212908, start_date=20250312T212917, end_date=20250312T212921
[2025-03-12T21:29:22.091+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T21:29:22.094+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 51 for task process_to_raw ('AwsS3Repository' object has no attribute 'upload_files_into_multiple_folders_test'; 196)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/usr/local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/usr/local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/app/src/command/manage_buckets.py", line 31, in ingest_data
    response = aws_s3.upload_files_into_multiple_folders_test(Bucket=bucket_name, data=data, folders=split)
AttributeError: 'AwsS3Repository' object has no attribute 'upload_files_into_multiple_folders_test'
[2025-03-12T21:29:22.141+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-12T21:29:22.182+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-12T21:29:22.187+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
