[2025-03-12T21:34:25.385+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T21:34:25.412+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_raw manual__2025-03-12T21:29:08.864088+00:00 [queued]>
[2025-03-12T21:34:25.425+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_raw manual__2025-03-12T21:29:08.864088+00:00 [queued]>
[2025-03-12T21:34:25.425+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-12T21:34:25.443+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_to_raw> on 2025-03-12 21:29:08.864088+00:00
[2025-03-12T21:34:25.453+0000] {standard_task_runner.py:72} INFO - Started process 299 to run task
[2025-03-12T21:34:25.470+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'process_to_raw', 'manual__2025-03-12T21:29:08.864088+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmpcrcefu_l']
[2025-03-12T21:34:25.473+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask process_to_raw
[2025-03-12T21:34:25.513+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-12T21:34:25.587+0000] {task_command.py:467} INFO - Running <TaskInstance: data_lake_pipeline.process_to_raw manual__2025-03-12T21:29:08.864088+00:00 [running]> on host ***-scheduler
[2025-03-12T21:34:25.726+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='process_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T21:29:08.864088+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T21:29:08.864088+00:00'
[2025-03-12T21:34:25.730+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T21:34:25.753+0000] {manage_buckets.py:24} INFO - [Data manager] Downloading data from HuggingFace...
[2025-03-12T21:34:28.420+0000] {manage_buckets.py:27} INFO - [Data manager] Data successfully downloaded.
[2025-03-12T21:34:28.421+0000] {manage_buckets.py:30} INFO - [Data manager] Transferring data to S3 bucket...
[2025-03-12T21:34:28.422+0000] {aws_s3_repository.py:133} INFO - [AWS S3] Uploading into raw ...
[2025-03-12T21:34:28.422+0000] {aws_s3_repository.py:136} INFO - [AWS S3] Transferring train data...
[2025-03-12T21:34:28.422+0000] {aws_s3_repository.py:148} CRITICAL - [AWS S3] Error while uploading data into raw ...
[2025-03-12T21:34:28.423+0000] {manage_buckets.py:42} CRITICAL - [Data manager] Error during uploading files to S3 bucket named raw
[2025-03-12T21:34:28.423+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T21:34:28.434+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T21:34:28.435+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=process_to_raw, run_id=manual__2025-03-12T21:29:08.864088+00:00, execution_date=20250312T212908, start_date=20250312T213425, end_date=20250312T213428
[2025-03-12T21:34:28.491+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T21:34:28.526+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-12T21:34:28.531+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
