[2025-03-12T16:51:43.620+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T16:51:43.639+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.transform_raw_to_staging manual__2025-03-12T16:50:59.037315+00:00 [queued]>
[2025-03-12T16:51:43.650+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.transform_raw_to_staging manual__2025-03-12T16:50:59.037315+00:00 [queued]>
[2025-03-12T16:51:43.650+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-12T16:51:43.666+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_raw_to_staging> on 2025-03-12 16:50:59.037315+00:00
[2025-03-12T16:51:43.671+0000] {standard_task_runner.py:72} INFO - Started process 237 to run task
[2025-03-12T16:51:43.676+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'transform_raw_to_staging', 'manual__2025-03-12T16:50:59.037315+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmpi_7f778d']
[2025-03-12T16:51:43.677+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask transform_raw_to_staging
[2025-03-12T16:51:43.694+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-12T16:51:43.727+0000] {task_command.py:467} INFO - Running <TaskInstance: data_lake_pipeline.transform_raw_to_staging manual__2025-03-12T16:50:59.037315+00:00 [running]> on host ***-scheduler
[2025-03-12T16:51:43.810+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='transform_raw_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T16:50:59.037315+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T16:50:59.037315+00:00'
[2025-03-12T16:51:43.812+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T16:51:43.822+0000] {manage_buckets.py:44} INFO - [Data manager] Prefix(s) : ['test', 'train', 'validation']
[2025-03-12T16:51:43.823+0000] {manage_buckets.py:46} INFO - [Data manager] Processessing data from : test
[2025-03-12T16:51:43.823+0000] {aws_s3_repository.py:33} INFO - [AWS S3] Getting list of raw's files...
[2025-03-12T16:51:43.835+0000] {aws_s3_repository.py:54} CRITICAL - [AWS S3] Error while processing data raw ... : An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2025-03-12T16:51:43.835+0000] {manage_buckets.py:46} INFO - [Data manager] Processessing data from : train
[2025-03-12T16:51:43.836+0000] {aws_s3_repository.py:33} INFO - [AWS S3] Getting list of raw's files...
[2025-03-12T16:51:43.841+0000] {aws_s3_repository.py:54} CRITICAL - [AWS S3] Error while processing data raw ... : An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2025-03-12T16:51:43.842+0000] {manage_buckets.py:46} INFO - [Data manager] Processessing data from : validation
[2025-03-12T16:51:43.842+0000] {aws_s3_repository.py:33} INFO - [AWS S3] Getting list of raw's files...
[2025-03-12T16:51:43.850+0000] {aws_s3_repository.py:54} CRITICAL - [AWS S3] Error while processing data raw ... : An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2025-03-12T16:51:43.850+0000] {manage_buckets.py:57} ERROR - [Data manager] Data processing failed.
[2025-03-12T16:51:43.851+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T16:51:43.860+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T16:51:43.861+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=transform_raw_to_staging, run_id=manual__2025-03-12T16:50:59.037315+00:00, execution_date=20250312T165059, start_date=20250312T165143, end_date=20250312T165143
[2025-03-12T16:51:43.934+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T16:51:43.959+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-12T16:51:43.964+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
