[2025-03-12T13:15:55.637+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T13:15:55.677+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_raw manual__2025-03-12T13:15:46.457665+00:00 [queued]>
[2025-03-12T13:15:55.699+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_raw manual__2025-03-12T13:15:46.457665+00:00 [queued]>
[2025-03-12T13:15:55.700+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-12T13:15:55.718+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_to_raw> on 2025-03-12 13:15:46.457665+00:00
[2025-03-12T13:15:55.724+0000] {standard_task_runner.py:72} INFO - Started process 556 to run task
[2025-03-12T13:15:55.730+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'process_to_raw', 'manual__2025-03-12T13:15:46.457665+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmpykdwyc__']
[2025-03-12T13:15:55.734+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask process_to_raw
[2025-03-12T13:15:55.758+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-12T13:15:55.803+0000] {task_command.py:467} INFO - Running <TaskInstance: data_lake_pipeline.process_to_raw manual__2025-03-12T13:15:46.457665+00:00 [running]> on host ***-scheduler
[2025-03-12T13:15:55.960+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='process_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T13:15:46.457665+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T13:15:46.457665+00:00'
[2025-03-12T13:15:55.961+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T13:15:55.985+0000] {manage_buckets.py:19} INFO - [Data manager] Downloading data from HuggingFace...
[2025-03-12T13:15:58.860+0000] {manage_buckets.py:22} INFO - [Data manager] Data successfully downloaded.
[2025-03-12T13:15:58.861+0000] {manage_buckets.py:25} INFO - [Data manager] Transferring data to S3 bucket...
[2025-03-12T13:15:58.861+0000] {aws_s3_repository.py:65} INFO - [AWS S3] ðŸš€ Uploading into raw ...
[2025-03-12T13:15:58.861+0000] {aws_s3_repository.py:68} INFO - [AWS S3] Transferring train data...
[2025-03-12T13:15:58.862+0000] {aws_s3_repository.py:69} INFO - [AWS S3] split_data: Dataset({
    features: ['text'],
    num_rows: 36718
})
[2025-03-12T13:15:59.012+0000] {aws_s3_repository.py:71} INFO - [AWS S3] Type of unit: <class 'str'>
[2025-03-12T13:15:59.013+0000] {aws_s3_repository.py:77} INFO - [AWS S3] Uploading ... to train/train_0.txt
[2025-03-12T13:15:59.373+0000] {aws_s3.py:33} CRITICAL - [S3 Client] Error : An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
[2025-03-12T13:15:59.377+0000] {aws_s3_repository.py:82} CRITICAL - [AWS S3] Error while uploading data into raw ...
[2025-03-12T13:15:59.378+0000] {manage_buckets.py:37} CRITICAL - [Data manager] Error during uploading files to S3 bucket named raw
[2025-03-12T13:15:59.379+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T13:15:59.398+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T13:15:59.399+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=process_to_raw, run_id=manual__2025-03-12T13:15:46.457665+00:00, execution_date=20250312T131546, start_date=20250312T131555, end_date=20250312T131559
[2025-03-12T13:15:59.451+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T13:15:59.470+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-12T13:15:59.475+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
